package common

const (
	NOT_FOUND_STUDENT_STATUS                    = "NOT_FOUND_STUDENT_STATUS"
	NOT_FOUND_MIN_CREDIT_CONFIG					= "NOT_FOUND_MIN_CREDIT_CONFIG"
	NOT_FOUND_MAX_CREDIT_CONFIG					= "NOT_FOUND_MAX_CREDIT_CONFIG"
	MIN_MAX_CONFIG_WRONG						= "MIN_MAX_CONFIG_WRONG"
	NOT_FOUND_SUBJECT_ID						= "NOT_FOUND_SUBJECT_ID"
	NOT_FOUND_COURSE_REGISTER					= "NOT_FOUND_COURSE_REGISTER"
	DUPLICATE_COURSE_REGISTER					= "DUPLICATE_COURSE_REGISTER"
)