server:
  port: 8000
  shutdown-timeout-sec: 5
service:
  name: register_course_check
  env: local

log:
  encoding: json
  tracing: false

debug:
  gin: release

redis:
  addresses: red-ch51g02k728glsiqtrvg:Fxq305SAkTE7WOJajJsa1x4Pc5quR5H9@singapore-redis.render.com:6379
  
cache:
  prefix: "lc"
  student-ttl-ms: 43200000 # 0.5 day
  min_max_credit-ttl-ms: 43200000 # 0.5 day

mysql:
  url: db4free.net:3306
  username: user_register
  password: 112358112358
  schema: test_register

authen:
  api-key: "abcd"


